<?php
/**
 * EventApi
 * PHP version 5
 *
 * @category Class
 * @package  kinoheld\GenericProviderClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * cinema
 *
 * cinema movie
 *
 * OpenAPI spec version: 1.0.0
 * Contact: sm@kinoheld.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.23
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace kinoheld\GenericProviderClient\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use kinoheld\GenericProviderClient\ApiException;
use kinoheld\GenericProviderClient\Configuration;
use kinoheld\GenericProviderClient\HeaderSelector;
use kinoheld\GenericProviderClient\ObjectSerializer;

/**
 * EventApi Class Doc Comment
 *
 * @category Class
 * @package  kinoheld\GenericProviderClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class EventApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getMovie
     *
     * movie details for the given movie id
     *
     * @param  int $chainId chain/company ID (required)
     * @param  int $cinemaId pass a cinema id to retrieve the associated movie (required)
     * @param  int $movieId pass a movie id to retrieve the movie details (required)
     *
     * @throws \kinoheld\GenericProviderClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \kinoheld\GenericProviderClient\Model\MovieItem
     */
    public function getMovie($chainId, $cinemaId, $movieId)
    {
        list($response) = $this->getMovieWithHttpInfo($chainId, $cinemaId, $movieId);
        return $response;
    }

    /**
     * Operation getMovieWithHttpInfo
     *
     * movie details for the given movie id
     *
     * @param  int $chainId chain/company ID (required)
     * @param  int $cinemaId pass a cinema id to retrieve the associated movie (required)
     * @param  int $movieId pass a movie id to retrieve the movie details (required)
     *
     * @throws \kinoheld\GenericProviderClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \kinoheld\GenericProviderClient\Model\MovieItem, HTTP status code, HTTP response headers (array of strings)
     */
    public function getMovieWithHttpInfo($chainId, $cinemaId, $movieId)
    {
        $returnType = '\kinoheld\GenericProviderClient\Model\MovieItem';
        $request = $this->getMovieRequest($chainId, $cinemaId, $movieId);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\kinoheld\GenericProviderClient\Model\MovieItem',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getMovieAsync
     *
     * movie details for the given movie id
     *
     * @param  int $chainId chain/company ID (required)
     * @param  int $cinemaId pass a cinema id to retrieve the associated movie (required)
     * @param  int $movieId pass a movie id to retrieve the movie details (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getMovieAsync($chainId, $cinemaId, $movieId)
    {
        return $this->getMovieAsyncWithHttpInfo($chainId, $cinemaId, $movieId)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getMovieAsyncWithHttpInfo
     *
     * movie details for the given movie id
     *
     * @param  int $chainId chain/company ID (required)
     * @param  int $cinemaId pass a cinema id to retrieve the associated movie (required)
     * @param  int $movieId pass a movie id to retrieve the movie details (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getMovieAsyncWithHttpInfo($chainId, $cinemaId, $movieId)
    {
        $returnType = '\kinoheld\GenericProviderClient\Model\MovieItem';
        $request = $this->getMovieRequest($chainId, $cinemaId, $movieId);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getMovie'
     *
     * @param  int $chainId chain/company ID (required)
     * @param  int $cinemaId pass a cinema id to retrieve the associated movie (required)
     * @param  int $movieId pass a movie id to retrieve the movie details (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getMovieRequest($chainId, $cinemaId, $movieId)
    {
        // verify the required parameter 'chainId' is set
        if ($chainId === null || (is_array($chainId) && count($chainId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $chainId when calling getMovie'
            );
        }
        // verify the required parameter 'cinemaId' is set
        if ($cinemaId === null || (is_array($cinemaId) && count($cinemaId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $cinemaId when calling getMovie'
            );
        }
        // verify the required parameter 'movieId' is set
        if ($movieId === null || (is_array($movieId) && count($movieId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $movieId when calling getMovie'
            );
        }

        $resourcePath = '/movie';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($chainId !== null) {
            $queryParams['chainId'] = ObjectSerializer::toQueryValue($chainId, null);
        }
        // query params
        if ($cinemaId !== null) {
            $queryParams['cinemaId'] = ObjectSerializer::toQueryValue($cinemaId, null);
        }
        // query params
        if ($movieId !== null) {
            $queryParams['movieId'] = ObjectSerializer::toQueryValue($movieId, null);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getSeats
     *
     * list of seats for the given show
     *
     * @param  int $chainId chain/company ID (required)
     * @param  int $showId Pass a show id to retrieve the associated shows. (required)
     *
     * @throws \kinoheld\GenericProviderClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \kinoheld\GenericProviderClient\Model\SeatItem[]
     */
    public function getSeats($chainId, $showId)
    {
        list($response) = $this->getSeatsWithHttpInfo($chainId, $showId);
        return $response;
    }

    /**
     * Operation getSeatsWithHttpInfo
     *
     * list of seats for the given show
     *
     * @param  int $chainId chain/company ID (required)
     * @param  int $showId Pass a show id to retrieve the associated shows. (required)
     *
     * @throws \kinoheld\GenericProviderClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \kinoheld\GenericProviderClient\Model\SeatItem[], HTTP status code, HTTP response headers (array of strings)
     */
    public function getSeatsWithHttpInfo($chainId, $showId)
    {
        $returnType = '\kinoheld\GenericProviderClient\Model\SeatItem[]';
        $request = $this->getSeatsRequest($chainId, $showId);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\kinoheld\GenericProviderClient\Model\SeatItem[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getSeatsAsync
     *
     * list of seats for the given show
     *
     * @param  int $chainId chain/company ID (required)
     * @param  int $showId Pass a show id to retrieve the associated shows. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSeatsAsync($chainId, $showId)
    {
        return $this->getSeatsAsyncWithHttpInfo($chainId, $showId)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getSeatsAsyncWithHttpInfo
     *
     * list of seats for the given show
     *
     * @param  int $chainId chain/company ID (required)
     * @param  int $showId Pass a show id to retrieve the associated shows. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSeatsAsyncWithHttpInfo($chainId, $showId)
    {
        $returnType = '\kinoheld\GenericProviderClient\Model\SeatItem[]';
        $request = $this->getSeatsRequest($chainId, $showId);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getSeats'
     *
     * @param  int $chainId chain/company ID (required)
     * @param  int $showId Pass a show id to retrieve the associated shows. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getSeatsRequest($chainId, $showId)
    {
        // verify the required parameter 'chainId' is set
        if ($chainId === null || (is_array($chainId) && count($chainId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $chainId when calling getSeats'
            );
        }
        // verify the required parameter 'showId' is set
        if ($showId === null || (is_array($showId) && count($showId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $showId when calling getSeats'
            );
        }

        $resourcePath = '/seats';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($chainId !== null) {
            $queryParams['chainId'] = ObjectSerializer::toQueryValue($chainId, null);
        }
        // query params
        if ($showId !== null) {
            $queryParams['showId'] = ObjectSerializer::toQueryValue($showId, null);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getShow
     *
     * show info for the given cinema and show ID
     *
     * @param  int $chainId chain/company ID (required)
     * @param  int $cinemaId cinema ID (required)
     * @param  int $showId show ID (required)
     *
     * @throws \kinoheld\GenericProviderClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \kinoheld\GenericProviderClient\Model\ShowItem
     */
    public function getShow($chainId, $cinemaId, $showId)
    {
        list($response) = $this->getShowWithHttpInfo($chainId, $cinemaId, $showId);
        return $response;
    }

    /**
     * Operation getShowWithHttpInfo
     *
     * show info for the given cinema and show ID
     *
     * @param  int $chainId chain/company ID (required)
     * @param  int $cinemaId cinema ID (required)
     * @param  int $showId show ID (required)
     *
     * @throws \kinoheld\GenericProviderClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \kinoheld\GenericProviderClient\Model\ShowItem, HTTP status code, HTTP response headers (array of strings)
     */
    public function getShowWithHttpInfo($chainId, $cinemaId, $showId)
    {
        $returnType = '\kinoheld\GenericProviderClient\Model\ShowItem';
        $request = $this->getShowRequest($chainId, $cinemaId, $showId);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\kinoheld\GenericProviderClient\Model\ShowItem',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getShowAsync
     *
     * show info for the given cinema and show ID
     *
     * @param  int $chainId chain/company ID (required)
     * @param  int $cinemaId cinema ID (required)
     * @param  int $showId show ID (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getShowAsync($chainId, $cinemaId, $showId)
    {
        return $this->getShowAsyncWithHttpInfo($chainId, $cinemaId, $showId)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getShowAsyncWithHttpInfo
     *
     * show info for the given cinema and show ID
     *
     * @param  int $chainId chain/company ID (required)
     * @param  int $cinemaId cinema ID (required)
     * @param  int $showId show ID (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getShowAsyncWithHttpInfo($chainId, $cinemaId, $showId)
    {
        $returnType = '\kinoheld\GenericProviderClient\Model\ShowItem';
        $request = $this->getShowRequest($chainId, $cinemaId, $showId);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getShow'
     *
     * @param  int $chainId chain/company ID (required)
     * @param  int $cinemaId cinema ID (required)
     * @param  int $showId show ID (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getShowRequest($chainId, $cinemaId, $showId)
    {
        // verify the required parameter 'chainId' is set
        if ($chainId === null || (is_array($chainId) && count($chainId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $chainId when calling getShow'
            );
        }
        // verify the required parameter 'cinemaId' is set
        if ($cinemaId === null || (is_array($cinemaId) && count($cinemaId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $cinemaId when calling getShow'
            );
        }
        // verify the required parameter 'showId' is set
        if ($showId === null || (is_array($showId) && count($showId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $showId when calling getShow'
            );
        }

        $resourcePath = '/show';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($chainId !== null) {
            $queryParams['chainId'] = ObjectSerializer::toQueryValue($chainId, null);
        }
        // query params
        if ($cinemaId !== null) {
            $queryParams['cinemaId'] = ObjectSerializer::toQueryValue($cinemaId, null);
        }
        // query params
        if ($showId !== null) {
            $queryParams['showId'] = ObjectSerializer::toQueryValue($showId, null);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getShows
     *
     * list of shows for the given cinema
     *
     * @param  int $chainId chain/company ID (required)
     * @param  int $cinemaId pass a cinema id to retrieve the associated shows (required)
     *
     * @throws \kinoheld\GenericProviderClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \kinoheld\GenericProviderClient\Model\ShowItem[]
     */
    public function getShows($chainId, $cinemaId)
    {
        list($response) = $this->getShowsWithHttpInfo($chainId, $cinemaId);
        return $response;
    }

    /**
     * Operation getShowsWithHttpInfo
     *
     * list of shows for the given cinema
     *
     * @param  int $chainId chain/company ID (required)
     * @param  int $cinemaId pass a cinema id to retrieve the associated shows (required)
     *
     * @throws \kinoheld\GenericProviderClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \kinoheld\GenericProviderClient\Model\ShowItem[], HTTP status code, HTTP response headers (array of strings)
     */
    public function getShowsWithHttpInfo($chainId, $cinemaId)
    {
        $returnType = '\kinoheld\GenericProviderClient\Model\ShowItem[]';
        $request = $this->getShowsRequest($chainId, $cinemaId);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\kinoheld\GenericProviderClient\Model\ShowItem[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getShowsAsync
     *
     * list of shows for the given cinema
     *
     * @param  int $chainId chain/company ID (required)
     * @param  int $cinemaId pass a cinema id to retrieve the associated shows (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getShowsAsync($chainId, $cinemaId)
    {
        return $this->getShowsAsyncWithHttpInfo($chainId, $cinemaId)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getShowsAsyncWithHttpInfo
     *
     * list of shows for the given cinema
     *
     * @param  int $chainId chain/company ID (required)
     * @param  int $cinemaId pass a cinema id to retrieve the associated shows (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getShowsAsyncWithHttpInfo($chainId, $cinemaId)
    {
        $returnType = '\kinoheld\GenericProviderClient\Model\ShowItem[]';
        $request = $this->getShowsRequest($chainId, $cinemaId);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getShows'
     *
     * @param  int $chainId chain/company ID (required)
     * @param  int $cinemaId pass a cinema id to retrieve the associated shows (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getShowsRequest($chainId, $cinemaId)
    {
        // verify the required parameter 'chainId' is set
        if ($chainId === null || (is_array($chainId) && count($chainId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $chainId when calling getShows'
            );
        }
        // verify the required parameter 'cinemaId' is set
        if ($cinemaId === null || (is_array($cinemaId) && count($cinemaId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $cinemaId when calling getShows'
            );
        }

        $resourcePath = '/shows';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($chainId !== null) {
            $queryParams['chainId'] = ObjectSerializer::toQueryValue($chainId, null);
        }
        // query params
        if ($cinemaId !== null) {
            $queryParams['cinemaId'] = ObjectSerializer::toQueryValue($cinemaId, null);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
