<?php
/**
 * CartItem
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * cinema
 *
 * cinema movie
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sm@kinoheld.de
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * CartItem Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CartItem implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CartItem';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'price_area_id' => 'int',
        'price_category_id' => 'int',
        'count' => 'int',
        'use_loyalty_free_entry' => 'bool',
        'seat_ids' => 'int[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'price_area_id' => null,
        'price_category_id' => null,
        'count' => null,
        'use_loyalty_free_entry' => null,
        'seat_ids' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'price_area_id' => false,
        'price_category_id' => false,
        'count' => false,
        'use_loyalty_free_entry' => false,
        'seat_ids' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'price_area_id' => 'priceAreaId',
        'price_category_id' => 'priceCategoryId',
        'count' => 'count',
        'use_loyalty_free_entry' => 'useLoyaltyFreeEntry',
        'seat_ids' => 'seatIds'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'price_area_id' => 'setPriceAreaId',
        'price_category_id' => 'setPriceCategoryId',
        'count' => 'setCount',
        'use_loyalty_free_entry' => 'setUseLoyaltyFreeEntry',
        'seat_ids' => 'setSeatIds'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'price_area_id' => 'getPriceAreaId',
        'price_category_id' => 'getPriceCategoryId',
        'count' => 'getCount',
        'use_loyalty_free_entry' => 'getUseLoyaltyFreeEntry',
        'seat_ids' => 'getSeatIds'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('price_area_id', $data ?? [], null);
        $this->setIfExists('price_category_id', $data ?? [], null);
        $this->setIfExists('count', $data ?? [], null);
        $this->setIfExists('use_loyalty_free_entry', $data ?? [], null);
        $this->setIfExists('seat_ids', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['price_area_id'] === null) {
            $invalidProperties[] = "'price_area_id' can't be null";
        }
        if ($this->container['price_category_id'] === null) {
            $invalidProperties[] = "'price_category_id' can't be null";
        }
        if ($this->container['count'] === null) {
            $invalidProperties[] = "'count' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets price_area_id
     *
     * @return int
     */
    public function getPriceAreaId()
    {
        return $this->container['price_area_id'];
    }

    /**
     * Sets price_area_id
     *
     * @param int $price_area_id The price area the seats/tickets should be selected for.
     *
     * @return self
     */
    public function setPriceAreaId($price_area_id)
    {
        if (is_null($price_area_id)) {
            throw new \InvalidArgumentException('non-nullable price_area_id cannot be null');
        }
        $this->container['price_area_id'] = $price_area_id;

        return $this;
    }

    /**
     * Gets price_category_id
     *
     * @return int
     */
    public function getPriceCategoryId()
    {
        return $this->container['price_category_id'];
    }

    /**
     * Sets price_category_id
     *
     * @param int $price_category_id The price category the seats/tickets should be selected for.
     *
     * @return self
     */
    public function setPriceCategoryId($price_category_id)
    {
        if (is_null($price_category_id)) {
            throw new \InvalidArgumentException('non-nullable price_category_id cannot be null');
        }
        $this->container['price_category_id'] = $price_category_id;

        return $this;
    }

    /**
     * Gets count
     *
     * @return int
     */
    public function getCount()
    {
        return $this->container['count'];
    }

    /**
     * Sets count
     *
     * @param int $count The amount of seats/tickets that should be selected for the given price category.
     *
     * @return self
     */
    public function setCount($count)
    {
        if (is_null($count)) {
            throw new \InvalidArgumentException('non-nullable count cannot be null');
        }
        $this->container['count'] = $count;

        return $this;
    }

    /**
     * Gets use_loyalty_free_entry
     *
     * @return bool|null
     */
    public function getUseLoyaltyFreeEntry()
    {
        return $this->container['use_loyalty_free_entry'];
    }

    /**
     * Sets use_loyalty_free_entry
     *
     * @param bool|null $use_loyalty_free_entry Set to true if this item has to be handled as a free item because of the loyalty points.
     *
     * @return self
     */
    public function setUseLoyaltyFreeEntry($use_loyalty_free_entry)
    {
        if (is_null($use_loyalty_free_entry)) {
            throw new \InvalidArgumentException('non-nullable use_loyalty_free_entry cannot be null');
        }
        $this->container['use_loyalty_free_entry'] = $use_loyalty_free_entry;

        return $this;
    }

    /**
     * Gets seat_ids
     *
     * @return int[]|null
     */
    public function getSeatIds()
    {
        return $this->container['seat_ids'];
    }

    /**
     * Sets seat_ids
     *
     * @param int[]|null $seat_ids If the cart is attached to a show/event with seat selection, this field is required and will contain the seat IDs that have been selected by the user for the given price category.
     *
     * @return self
     */
    public function setSeatIds($seat_ids)
    {
        if (is_null($seat_ids)) {
            throw new \InvalidArgumentException('non-nullable seat_ids cannot be null');
        }
        $this->container['seat_ids'] = $seat_ids;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


