<?php
/**
 * ShowItemTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  kinoheld\GenericProviderClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * cinema
 *
 * cinema movie
 *
 * OpenAPI spec version: 1.0.0
 * Contact: sm@kinoheld.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.13
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace kinoheld\GenericProviderClient;

/**
 * ShowItemTest Class Doc Comment
 *
 * @category    Class
 * @description ShowItem
 * @package     kinoheld\GenericProviderClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ShowItemTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ShowItem"
     */
    public function testShowItem()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "movieId"
     */
    public function testPropertyMovieId()
    {
    }

    /**
     * Test attribute "duration"
     */
    public function testPropertyDuration()
    {
    }

    /**
     * Test attribute "beginning"
     */
    public function testPropertyBeginning()
    {
    }

    /**
     * Test attribute "saleStart"
     */
    public function testPropertySaleStart()
    {
    }

    /**
     * Test attribute "saleEnd"
     */
    public function testPropertySaleEnd()
    {
    }

    /**
     * Test attribute "auditoriumId"
     */
    public function testPropertyAuditoriumId()
    {
    }

    /**
     * Test attribute "seatSelectionAvailable"
     */
    public function testPropertySeatSelectionAvailable()
    {
    }

    /**
     * Test attribute "icaaId"
     */
    public function testPropertyIcaaId()
    {
    }

    /**
     * Test attribute "languageAudio"
     */
    public function testPropertyLanguageAudio()
    {
    }

    /**
     * Test attribute "languageSubtitle"
     */
    public function testPropertyLanguageSubtitle()
    {
    }

    /**
     * Test attribute "priceAreas"
     */
    public function testPropertyPriceAreas()
    {
    }

    /**
     * Test attribute "ticketsTotal"
     */
    public function testPropertyTicketsTotal()
    {
    }

    /**
     * Test attribute "ticketsSold"
     */
    public function testPropertyTicketsSold()
    {
    }

    /**
     * Test attribute "ticketsFree"
     */
    public function testPropertyTicketsFree()
    {
    }

    /**
     * Test attribute "flags"
     */
    public function testPropertyFlags()
    {
    }
}
