<?php
/**
 * EventApiTest
 * PHP version 5
 *
 * @category Class
 * @package  kinoheld\GenericProviderClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * cinema
 *
 * cinema movie
 *
 * OpenAPI spec version: 1.0.0
 * Contact: sm@kinoheld.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.23
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace kinoheld\GenericProviderClient;

use kinoheld\GenericProviderClient\Configuration;
use kinoheld\GenericProviderClient\ApiException;
use kinoheld\GenericProviderClient\ObjectSerializer;

/**
 * EventApiTest Class Doc Comment
 *
 * @category Class
 * @package  kinoheld\GenericProviderClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class EventApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getMovie
     *
     * movie details for the given movie id.
     *
     */
    public function testGetMovie()
    {
    }

    /**
     * Test case for getSeats
     *
     * list of seats for the given show.
     *
     */
    public function testGetSeats()
    {
    }

    /**
     * Test case for getShow
     *
     * show info for the given cinema and show ID.
     *
     */
    public function testGetShow()
    {
    }

    /**
     * Test case for getShows
     *
     * list of shows for the given cinema.
     *
     */
    public function testGetShows()
    {
    }
}
