<?php
/**
 * EventApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Kinoheld\GenericProviderClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * cinema
 *
 * cinema movie
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sm@kinoheld.de
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Kinoheld\GenericProviderClient\Test\Api;

use \Kinoheld\GenericProviderClient\Configuration;
use \Kinoheld\GenericProviderClient\ApiException;
use \Kinoheld\GenericProviderClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * EventApiTest Class Doc Comment
 *
 * @category Class
 * @package  Kinoheld\GenericProviderClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class EventApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getMovie
     *
     * movie details for the given movie id.
     *
     */
    public function testGetMovie()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getSeats
     *
     * list of seats for the given show.
     *
     */
    public function testGetSeats()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getShow
     *
     * show info for the given cinema and show ID.
     *
     */
    public function testGetShow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getShows
     *
     * list of shows for the given cinema.
     *
     */
    public function testGetShows()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
