<?php
/**
 * LoyaltyApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Kinoheld\GenericProviderClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * cinema
 *
 * cinema movie
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sm@kinoheld.de
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Kinoheld\GenericProviderClient\Test\Api;

use \Kinoheld\GenericProviderClient\Configuration;
use \Kinoheld\GenericProviderClient\ApiException;
use \Kinoheld\GenericProviderClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * LoyaltyApiTest Class Doc Comment
 *
 * @category Class
 * @package  Kinoheld\GenericProviderClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class LoyaltyApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for loyaltyGet
     *
     * get the loyalty card.
     *
     */
    public function testLoyaltyGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
